Bricks Documentation
mercadopago/sdk-js pull request #64
Opened 2022-05-23 14:11 UTC by meliguicarvalho

Added Bricks documentation and separated individual modules.

2022-05-24 19:39 UTC, AleFossati approved these changes

2022-05-27 13:27 UTC, lucmantovani requested changes

2022-05-27 13:27 UTC, lucmantovani commented on README.md
>  ## API
Adicionar opção de `trackingDisabled` na lista de options

2022-05-27 13:27 UTC, lucmantovani commented on API/core-methods.md
> +|`advancedFraudPrevention` |`true\|false`| true | *boolean* | Set the advanced fraud prevention status | **OPTIONAL** |
```suggestion
|Option name|Values|Default|Type|Description||
|-|-|-|-|-|-|
|`locale` |`es-AR`<br>`es-CL`<br>`es-CO`<br>`es-MX`<br>`es-VE`<br>`es-UY`<br>`es-PE`<br>`pt-BR`<br>`en-US`|Browser default locale | *string* | Set the locale | **OPTIONAL** |
|`advancedFraudPrevention` |`true\|false`| true | *boolean* | Set the advanced fraud prevention status | **OPTIONAL** |
|`trackingDisabled` |`true\|false`| false | *boolean* | Enable/disable tracking of generic usage metrics | **OPTIONAL** |
```

Adicionei a descrição do `trackingDisabled`, mas talvez podemos pensar em uma frase melhor para deixar mais claro que não coletamos dados sensíveis.

2022-05-27 13:27 UTC, lucmantovani commented on API/fields.md
> +|`advancedFraudPrevention` |`true\|false`| true | *boolean* | Set the advanced fraud prevention status | **OPTIONAL** |
Adicionar também o parâmetro `trackingDisabled`

2022-05-27 16:53 UTC, meliguicarvalho commented on API/bricks/card-payment.md
> +| `onSubmit` | It is called when the user clicks on the submit button | **OPTIONAL** | `void` | `CardData` |
Sobre o callback onSubmit, realmente é opcional, porem para usar o Brick sem esse parametro, o integrador deve esconder o botao de pagamento, e chamar o metodo getFormData.  Sobre os parametros, voce esta correto, vou ajustar

2022-06-06 11:33 UTC, lucmantovani approved these changes

2022-06-06 11:34 UTC, merged